# Generated by Django 5.1.3 on 2024-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
