# Generated by Django 5.1.3 on 2024-12-04 12:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=".images./posts/default.jpg",
                upload_to=blog.models.postImageDirectory,
            ),
        ),
    ]
