# Generated by Django 5.1.3 on 2024-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="Your email used as username",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
    ]
