# Generated by Django 5.1.3 on 2024-11-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", editable=False, max_length=255),
        ),
    ]
